# Generated by Django 4.0 on 2025-09-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='info',
        ),
        migrations.AlterField(
            model_name='historylevel',
            name='image',
            field=models.ManyToManyField(blank=True, to='game_web.History_images'),
        ),
    ]
