# Generated by Django 4.0 on 2025-09-13 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_web', '0002_remove_object_info_alter_historylevel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_objects', to='game_web.level'),
        ),
    ]
